### ISSUE TITLE
Resize methods

### ISSUE THREAD

**Issue by Zarxrax** [palant/image-resize-comfyui#1]
Can you add additional resize methods other than bicubic?

**Comment by palant** [comment]
Could you tell me what the point is? Bicubic seems to do a good job in any of the relevant cases, and resizing performance shouldn’t matter compared to the rest of the pipeline.

**Comment by Zarxrax** [comment]
Actually, after some more testing, the output from your node looks like nearest neighbor resize for some reason. I did a bicubic resize in another application and it looks fine. So I guess my issue isn't necessarily that there need to be more resize methods, but maybe that there is some issue causing the output to look horrible.

See the two attached images. In the one I saved from your node, the image becomes a mess of pixels and the halftone pattern becomes enlarged and very prominent.

![test](https://github.com/palant/image-resize-comfyui/assets/16127268/0ca4809a-21c3-405b-93d9-23ddc1e543ed)
![test_comfy](https://github.com/palant/image-resize-comfyui/assets/16127268/04717e79-2d38-4da5-b361-01e438ba55d2)

**Comment by palant** [comment]
Interesting. Can you give me the original image as well? I’ll look into it.

**Comment by Zarxrax** [comment]
I wouldn't normally be loading an actual manga page into comfyui, but it just seemed like a good image to test the resize on.

![Rooster Fighter - c001 (v01) - p026  dig   VIZ Media   LuCaZ](https://github.com/palant/image-resize-comfyui/assets/16127268/dda3f427-5a94-4818-b387-b92026d67818)

**Comment by palant** [comment]
Thank you, got your results reproduced. Also confirmed that the regular Upscale Image node produces the exact same results when using bilinear and bicubic method (nearest-exact looks slightly differently but not actually better). Will check this out but given how we are talking about PyTorch code this might take some time.

**Comment by palant** [comment]
At least I can already suspect where the issue is: the PyTorch function in question is called `upsample_bicubic2d`, so it’s probably not meant to be used for reducing image size.

**Comment by palant** [comment]
Found the clue in the documentation:

> Using anti-alias option together with align_corners=False, interpolation result would match Pillow result for downsampling operation. 

In fact, adding `antialias=True` fixes this issue. I’ll still need to check how this parameter impacts upscaling, not today any more.
