### ISSUE TITLE
input is pixels

### ISSUE THREAD

**Issue by johndpope** [palant/image-resize-comfyui#3]
![workflow (1)](https://github.com/palant/image-resize-comfyui/assets/289994/8a51a84c-20de-4132-b536-13490ba180b4)

am using your plugin with https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID

but it hits a snag. 
my input image is 1024x1024

I load your node in try a bunch of settings but errors
![Screenshot from 2024-01-24 16-19-49](https://github.com/palant/image-resize-comfyui/assets/289994/df604155-6043-4aba-beb2-3a18689b9f72)

your asking for pixels - not an image for input. how can I do format image to that?

**Comment by johndpope** [comment]
weird I try an image from the zho library - and it works.

**Comment by palant** [comment]
This doesn’t look like an image with my node. I don’t know why InstantID Generation produced a string as an image but I suggest you ask its author.

**Comment by johndpope** [comment]
FYI . I think it’s expecting only png - I had used a jpeg that successfully resized but then maybe broke things.

**Comment by palant** [comment]
I doubt that. Once the image loads, it’s always represented as pixels in memory no matter what the original image format was.

**Comment by johndpope** [comment]
ok - good to know. thx
