### ISSUE TITLE
Conflicted nodes

### ISSUE THREAD

**Issue by poluramus** [palant/image-resize-comfyui#4]
It appears there's a conflict with this node: https://github.com/taabata/LCM_Inpaint_Outpaint_Comfy

If your node is included in a workflow and LCM_Inpaint_Outpaint_Comfy is installed while your node isn't, it will default to using LCM_Inpaint_Outpaint_Comfy instead.

Additionally, in a scenario where neither node is installed and a workflow containing your node is loaded, both nodes are visible under "install missing node."

I'm uncertain if the issue lies with your node.

**Comment by palant** [comment]
Yes, they also have a node called ImageResize. I don’t think there is an issue with either tool, ComfyUI simply has no way of resolving naming conflicts. And naming conflicts are bound to happen.

**Comment by poluramus** [comment]
It might be why some nodes add a unique ID at the end like "KSampler (Efficient)". That would be useful, I have 4 different ResizeImage node, which can be confusing haha.

Thank for the quick answer sir. I love your node. Very useful 👍
