### ISSUE TITLE
resize mask issue

### ISSUE THREAD

**Issue by Abu7Z** [palant/image-resize-comfyui#5]
Hello,really appreciate your work! But when i connect [padding image for outpainting]'s mask to the [mask] socket in this node. It just report error. I wonder if i am doing something wrong
Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [1542] and output size of (896, 1542). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.
![image](https://github.com/palant/image-resize-comfyui/assets/169167728/425f5508-3799-422d-8415-fe06156856df)

**Comment by palant** [comment]
The title “LCM Inpaint-Outpaint” is suspicious. It refers to https://github.com/taabata/LCM_Inpaint_Outpaint_Comfy/ which has a different component named Image Resize. Maybe there is a conflict here?

**Comment by palant** [comment]
This might not have been entirely obvious, but this is waiting on your feedback. Does this issue still occur if you disable LCM_Inpaint_Outpaint_Comfy?

**Comment by Abu7Z** [comment]
> The title “LCM Inpaint-Outpaint” is suspicious. It refers to https://github.com/taabata/LCM_Inpaint_Outpaint_Comfy/ which has a different component named Image Resize. Maybe there is a conflict here?

Yes, there is a conflict here. Disable LCM_Inpaint_Outpaint_Comfy will solve the error. Thank you very much!
